import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import eccChat from "../../Assets/Projects/eccChat.png";
import handGesture from "../../Assets/Projects/handGesture.png";
import unetSegmentation from "../../Assets/Projects/unetSegmentation.png";
import inventorySystem from "../../Assets/Projects/inventorySystem.png";
import webScraping from "../../Assets/Projects/webScraping.png";
import deepfakeAudio from "../../Assets/Projects/deepfakeAudio.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Projects </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={eccChat}
              isBlog={false}
              title="ECC Encrypted Chat Application"
              description="Created a secure end-to-end encrypted chat application using Java, Socket Programming, ECC, and ECDH for secure communication and data privacy."
              ghLink="https://github.com/jatin/ecc-encrypted-chat"
              demoLink="https://example.com/ecc-chat-demo"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={handGesture}
              isBlog={false}
              title="Hand Gesture Controlled Media Player"
              description="Built a gesture recognition system using OpenCV and ML for controlling media player functions through hand gestures, enabling touch-free interaction."
              ghLink="https://github.com/jatin/hand-gesture-media-player"
              demoLink="https://example.com/hand-gesture-demo"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={unetSegmentation}
              isBlog={false}
              title="Image Segmentation with UNET"
              description="Developed a segmentation model using CNN and UNET architecture for accurate image segmentation on medical and satellite images."
              ghLink="https://github.com/jatin/unet-image-segmentation"
              demoLink="https://example.com/unet-segmentation-demo"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={inventorySystem}
              isBlog={false}
              title="Inventory Management System"
              description="Created an Inventory Management System using Django with features like product add/delete/view. Implemented CRUD operations for product management."
              ghLink="https://github.com/jatin/inventory-management-system"
              demoLink="https://example.com/inventory-demo"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={webScraping}
              isBlog={false}
              title="Web Scraping Project"
              description="Performed web scraping of dynamic websites using Selenium, BeautifulSoup4, and Requests to extract structured data from multiple sources."
              ghLink="https://github.com/jatin/web-scraping-project"
              demoLink="https://example.com/web-scraping-demo"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={deepfakeAudio}
              isBlog={false}
              title="Deepfake Audio Detection"
              description="Built a deep learning-based system to detect spoofed audio generated by TTS and Voice Conversion using spectrogram analysis."
              ghLink="https://github.com/jatin/deepfake-audio-detection"
              demoLink="https://example.com/deepfake-audio-demo"
            />
          </Col>
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
